-- AlterTable
ALTER TABLE "Chat" ADD COLUMN     "user2ChatClearedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "userChatClearedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
